[platformio]
default_envs = uno, esp32cam
src_dir = src

[env]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+

[env:uno]
platform = atmelavr
board = uno
build_src_filter = +<uno.cpp>
lib_deps =
    adafruit/Adafruit AMG88xx Library

[env:esp32cam]
platform = espressif32
board = esp32cam
build_src_filter = +<esp32cam.cpp>
; Select the AI-Thinker ESP32-CAM board profile.
board_build.flash_mode = dio
